import * as path from "node:path";
import * as fs from "node:fs";
import { execSync } from "node:child_process";
import { SnykTool } from "./tools/SnykTool";
import { AIEngine } from "./tools/AIEngine";
import { RemediationExecutor } from "./tools/RemediationExecutor";

async function startAgent() {
    console.log("Security Agent started...");

    const victimPath = path.resolve(__dirname, "..", "..", "victim-app");

    const snyk = new SnykTool(victimPath);
    const ai = new AIEngine();
    const executor = new RemediationExecutor(victimPath);
    
    const MAX_ATTEMPTS = 3;
    let attempt = 1;
    let success = false;

    while (attempt <= MAX_ATTEMPTS && !success) {
        console.log(`--- Attempt ${attempt} ---`);
        const vulnerabilities = await snyk.scan();

        if (vulnerabilities.length > 0) {
            const highSeverity = vulnerabilities.filter(v => v.severity === 'high' || v.severity === 'critical');
            
            console.log(`Found ${vulnerabilities.length} vulnerabilities (${highSeverity.length} High/Critical).`);
            
            const plan = await ai.suggestFix(vulnerabilities);

            if (plan) {
                executor.createBackup();

                console.log("Executing remediation plan...");
                await executor.execute(plan);

                console.log("Running regression tests...");
                try {
                    execSync('npm test', { 
                        cwd: victimPath, 
                        stdio: 'inherit',
                        env: { 
                            ...process.env, 
                            NODE_OPTIONS: '--experimental-vm-modules --no-warnings' 
                        }
                    });
                    
                    const reportPath = path.join(victimPath, 'report.json');
                    if (fs.existsSync(reportPath)) {
                        fs.unlinkSync(reportPath);
                    }

                    attempt++;
                } catch (testError) {
                    console.error("REGRESSION DETECTED: Security fix compromised application logic.");
                    console.log("Aborting to prevent functional breakage.");
                    executor.rollback();
                    break; 
                }
            } else {
                console.log("No remediation plan could be generated by the AI engine.");
                break;
            }
        } else {
            console.log("No vulnerabilities detected.");
            success = true;
        }
    }

    if (!success) {
        console.log("Remediation unsuccessful or stopped due to regression.");
    } else {
        console.log("All vulnerabilities addressed and verified by tests.");
    }
}

startAgent();