import * as path from "node:path";
import { SnykTool } from "./tools/SnykTool";
import { AIEngine } from "./tools/AIEngine";
import { RemediationExecutor } from "./tools/RemediationExecutor";

async function startAgent() {
    console.log("Security Agent started...");

    const victimPath = path.resolve(__dirname, "..", "..", "victim-app");

    const snyk = new SnykTool(victimPath);
    const ai = new AIEngine();
    const executor = new RemediationExecutor(victimPath);

    const vulnerabilities = await snyk.scan();
    console.log("Vulnerabilities found:", vulnerabilities);

    if (vulnerabilities.length > 0) {
        const highSeverity = vulnerabilities.filter(v => v.severity === 'high' || v.severity === 'critical');
        console.table(highSeverity.map((v) => ({
            ID: v.id,
            Title: v.title,
            Package: v.packageName,
            Version: v.version,
            Severity: v.severity,
            FixedIn: v.fixedIn.join(', ') || 'N/A'
        })));

        console.log(`Total vulnerabilities: ${vulnerabilities.length}`);
        const plan = await ai.suggestFix(vulnerabilities);

        if (plan) {
            await executor.execute(plan);
        } else {
            console.log("No remediation plan could be generated by the AI engine.");
        }
    } else {
        console.log("No vulnerabilities detected.");
    }
}

startAgent();