name: Lostal Unit Test Trigger
on: [push, workflow_dispatch]

jobs:
    test-unit-tests:
        uses: ./.github/workflows/reusable-nodejs-unit-tests.yml
        with:
            target_repository: ${{ github.repository }}
            target_subdirectory: "patients/vulnerable-api-app"
            target_test_file: ""
            llm_url: "http://host.docker.internal:1234/v1" 
            llm_model_name: "openai/gpt-oss-20b"
            ai_tools_ref: "feature-add-unit-tests-workflow"
            run_environment: "dev"
        secrets:
            LM_API_KEY: ${{ secrets.LM_API_KEY }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            
